services:

  db:
    image: postgres:14.5-alpine
    shm_size: 512m
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    restart: on-failure

  redis:
    container_name: datawiz_project-redis
    image: redis:alpine
    restart: always
    ports:
      - '6378:6379'

volumes:
  postgres_data:
