services:

  db:
    container_name: datawiz_project-db
    image: postgres:14.5-alpine
    shm_size: 512m
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    restart: on-failure

  web:
    container_name: datawiz_project-web
    build: .
    command: pipenv run start
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: on-failure

  redis:
    container_name: datawiz_project-redis
    image: redis:alpine
    restart: always
    ports:
      - "6378:6379"

volumes:
  postgres_data:
