# Generated by Django 3.2.15 on 2023-05-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopgroup',
            name='left',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='shopgroup',
            name='level',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='shopgroup',
            name='right',
            field=models.BigIntegerField(),
        ),
    ]
