# Generated by Django 3.2.15 on 2023-05-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
    ]
