# Generated by Django 3.2.15 on 2023-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
    ]
